name: Android CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:  
    - uses: actions/checkout@v3
    
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload html test report
      uses: actions/upload-artifact@v3
      with:
        name: lint.html
        path: app/build/reports/lint-results-debug.html

    - name: Run tests
      run: ./gradlew test

    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: unit_test_report
        path: app/build/reports/tests/testDebugUnitTest/

    - name: Run espresso tests
      uses: reactivecircus/android-emulator-runner@v3
      with:
        api-level: 33
        script: ./gradlew connectedCheck

    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: instrumentation_test_report
        path: app/build/reports/androidTests/connected/  

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: expense-manager.apk
        path: app/build/outputs/apk/debug/app-debug.apk

      
    
